name: Auto-commit to branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make changes
        run: echo "Hello, World!" > output.txt
      - name: Commit changes
        run: |
          git config --global user.email "akoritala@tapestry.com"
          git config --global user.name "Venkatesh"
          git checkout -b Rajahmundary12.0ROW
          git add output.txt
          git commit -m "Auto-commit changes"
          git push origin Rajahmundary12.0ROW

