name: Auto-commit code

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Rajahmundary12.0ROW
        run: |
          git config user.name "Your Name"
          git config user.email "venkatesh.sony@gmail.com"
          git checkout main
          git merge Rajahmundary12.0/Rajahmundary12.0ROW
          git push
