name: Auto-commit code

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Rajahmundary12.0
        run: |
          git config user.name "Mygapula"
          git config user.email "venkatesh.sony@gmail.com"
          git checkout main
          git merge Chennai1/Chennai2
          git push
