name: Auto-commit code

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Rajahmundary12.0ROW
        run: |
          git config user.name "Rajahmundary12.0ROW"
          git config user.email "venkatesh.sony@gmail.com.com"
          git checkout main
          git merge chennai1/Chennai2
          git push
